### ISSUE TITLE
20小时前期蓝图包/中期/绿糖180好像缺少了一块

### ISSUE THREAD

**Issue by CodFrm** [DSPBluePrints/FactoryBluePrints#102]
![image](https://github.com/DSPBluePrints/FactoryBluePrints/assets/22783163/cc8b31e0-5d31-473a-8e18-d065a70fdda1)

好像缺少了左边这些产物

**Comment by bWFuanVzYWth** [comment]
我粗略检查了一下，没有看出问题，这些标识应该只是告诉你输入这些材料，不代表作者必须从原矿开始提供全套产线
