### ISSUE TITLE
如何使用密铺模板

### ISSUE THREAD

**Issue by HernandoR** [DSPBluePrints/FactoryBluePrints#13]
大多数密铺工厂使用了重叠的传送带，如何将其连接到(out) 分立的两个传送带。以及，如何将分立传送带连接上（in）重叠的传送带？

**Comment by bWFuanVzYWth** [comment]
这你应该去搜密铺技巧，或者加一个蓝图交流群。蓝图仓库重点在分类整理来自社区的蓝图，而非提供蓝图制作教学
