### ISSUE TITLE
无带又活了，建议撤销commit

### ISSUE THREAD

**Issue by LittleNightmare** [DSPBluePrints/FactoryBluePrints#14]
就比原来的多几个步骤，可以看[置顶评论](https://b23.tv/p3x3r7F)

>关于戴森球的无带蓝图，我今天试验也仍然可用，具体方式为先铺设一遍，然后删除所有传送带，再重新再铺设一次（这次使用shift+enter只铺设传送带）

**Comment by bWFuanVzYWth** [comment]
>最近看到好多玩家开始玩无带流，这个将来必然是不允许的，所以我们不建议使用无带流以防玩家不必要的损失哦~
以上是制作组成员**鱼白白**原话。
主观上制作组认定无带流属于恶性bug，客观上制作组也对无带流进行了修复。我认为这次的无带流复活与其说是修复中止不如说是修复未遂，不代表无带流在性质上能恢复成常规蓝图的地位。
另外对蓝图仓库来说，历史博物馆内的蓝图同样会被永久保留，并且同样会长期维护更新。如果你只是希望继续使用无带流蓝图，请勿担心，毕竟这只是一个分类的问题。
