### ISSUE TITLE
错误的cmd语法导致双击更新失效

### ISSUE THREAD

**Issue by Rhilip** [DSPBluePrints/FactoryBluePrints#52]
我使用scoop安装的git（所以git目录并不是在bat文件查找的位置）
在双击bat文件更新时会出现以下提示

![image](https://user-images.githubusercontent.com/13842140/230769619-cc01a259-d46c-48ed-87d6-12b7638b3028.png)

查看了下，应该是此处的写法有问题，管道字符没有正确的escape，需要把 `忽略 | Warning:` 改成 `忽略 ^| Warning:`

https://github.com/DSPBluePrints/FactoryBluePrints/blob/8597b8ef0819de1b261a0e91a4f324448b4e6919/%E5%8F%8C%E5%87%BB%E6%9B%B4%E6%96%B0%E8%93%9D%E5%9B%BE%E4%BB%93%E5%BA%93.bat#L19-L23

ref: [How to pass a quoted pipe character to cmd.exe?](https://stackoverflow.com/a/1200278)

**Comment by bWFuanVzYWth** [comment]
已修复，感谢反馈
