### ISSUE TITLE
使用高层进爪特性的蓝图是否应移动到历史博物馆？

### ISSUE THREAD

**Issue by pnck** [DSPBluePrints/FactoryBluePrints#53]
如这个：
https://github.com/DSPBluePrints/FactoryBluePrints/blob/342a3bee105c7ad437709e2babb01b755504d4cf/%E4%B8%80%E5%A1%94%E4%B8%80%E7%89%A9%20one%20tower%20one%20thing/1800%E7%BB%BF%E9%A9%AC%E8%BE%BE%EF%BC%88%E4%B8%80%E7%BA%A7%E7%9F%BF%E7%89%A9%E8%BE%93%E5%85%A5%EF%BC%89%E5%85%A8%E5%A2%9E%E4%BA%A7.txt#L1

这个：
https://github.com/DSPBluePrints/FactoryBluePrints/blob/342a3bee105c7ad437709e2babb01b755504d4cf/%E4%B8%80%E5%A1%94%E4%B8%80%E7%89%A9%20one%20tower%20one%20thing/%E8%B6%85%E7%BA%A7%E7%A3%81%E5%9C%BA%E7%8E%AF1800.txt#L1

应该是同一个作者？

都使用了超过+1.5层的进爪，因而直接粘贴后会显示分拣器链接断开标志。 请问这些超过1.5层进爪无法直接粘贴的蓝图是否也应归为无效移到博物馆里呢？

**Comment by XiaoTu-19** [comment]
copy ，已解决

**Comment by XiaoTu-19** [comment]
copy ，已解决
