### ISSUE TITLE
新手不会上传

### ISSUE THREAD

**Issue by newbienoobplayer** [DSPBluePrints/FactoryBluePrints#73]
大佬们好,我是GitHub的新手菜鸟 我应该怎么上传仙术蓝图, 我没有qq

**Comment by zxcvbnm3057** [comment]
不知道这个库推送权限怎么设置的

正常流程是你fork一下这个库到自己的账号里，然后把你自己账号的库pull下来，在库里修改，然后push上去，修改是在自己账号里做的，弄完以后，开一个pull request，这个库的开发者看情况就会merge，就完成contribute了

百度搜搜应该有教程吧

**Comment by newbienoobplayer** [comment]
呃。。。，兄弟你那念了一串英语我没看懂啊

**Comment by newbienoobplayer** [comment]
请问什么是库？

**Comment by zxcvbnm3057** [comment]
呃。。。这个，这些都是git命令，我也不知道咋翻译啊，你就搜搜怎么给别人的库提pr，应该就有教程了

**Comment by zxcvbnm3057** [comment]
这个dspblueprints就是库，这东西就这么叫，我也不太会解释，就是一堆文件放一起

**Comment by newbienoobplayer** [comment]
好吧谢谢

**Comment by bWFuanVzYWth** [comment]
自行搜索相关教程，无关问题将被关闭
