### ISSUE TITLE
能否更新一下蓝图介绍

### ISSUE THREAD

**Issue by zxcvbnm3057** [DSPBluePrints/FactoryBluePrints#74]
首先非常感谢各位贡献者设计和上传了这么多的蓝图。

可是蓝图太多也不完全是好事啊，一年多没玩了拉下来进游戏一看，根本不知道哪个是用什么生产什么的。。。。

如果不是太麻烦的话希望可以补充一下蓝图的输入输出和生产消耗速率，谢谢！

**Comment by bWFuanVzYWth** [comment]
主仓库达到设计目标就收，不保证质量
精选蓝图移步https://github.com/DSPBluePrints/Hard-Quality-FactoryBluePrints

**Comment by zxcvbnm3057** [comment]
。。刚在沙盒里挨个试玩记到TXT里玩了十个小时。。原来有选过的。
