### ISSUE TITLE
关于release提点建议

### ISSUE THREAD

**Issue by zxcvbnm3057** [DSPBluePrints/FactoryBluePrints#75]
看了下release压缩包，虽然清空了工作区，但是仍保留了历史git提交，这个对于连git都不会安装的玩家来说是没有意义的，再考虑到国内访问github速度奇慢，建议优化掉这部分来节省时间

下面是我本地测试的命令及效果

![RKDQ1X6~%L1E) 4HMEEH3A](https://github.com/DSPBluePrints/FactoryBluePrints/assets/48760372/a116d1a9-7c0a-44d2-9edb-feea31473c96)

测试命令是下面两行，没有截全
```powershell
git clone --bare FactoryBluePrints my_project.git
git clone my_project.git my
```

右上角是用这种方法还原的本地库目录与git clone --depth==1的对比，缺少的两个文件是远程head信息

下面中间的文件夹是没有历史提交的git目录，由于我是要展示还原效果，就没有直接还原工作区，把这个文件夹改名为.git即可代替release里的.git文件夹。

可以看到减小了60MB的体积，约合1/6

**Comment by bWFuanVzYWth** [comment]
因为我希望可以从任意一位用户那边恢复出蓝图仓库的完整内容。
每个release在打包时都会执行一次`$(GIT) repack -a -d --depth=4095 --window=4095`以尽量减小体积，相关内容可以自行查看Makefile，如果有无副作用的优化那我当然非常乐意，牺牲信息完整的恕不接受。

**Comment by zxcvbnm3057** [comment]
如果你指信息完整性的是在玩家电脑里保留一份你们所有人所有提交的所有变更内容的话，那确实牺牲了。你可以根据我附的截图来看到底有没有丢失文件，或者你自己试一试这两行命令的效果。蓝图代码本身就是编码压缩过得，再使用repack压缩效果并不明显。你们对比一下看看吧。

**Comment by bWFuanVzYWth** [comment]
如果你想从蓝图下手可以参考我写的https://github.com/bWFuanVzYWth/dspbptk，可以把大部分蓝图压缩10%的样子

**Comment by zxcvbnm3057** [comment]
不，我并不在意蓝图多大。国内连接github的网速你应该也知道吧，为什么要在发布版里增加一部分对玩家完全不必要的内容呢，当然是否保留是你们的决定，我只是看见前面那个issue说更新报错才注意到这个蓝图包居然这么大。你那个插件不适合用在这个库里，除非每次执行更新都做一次压缩验证。

**Comment by bWFuanVzYWth** [comment]
完全不必要的内容可不止这60mb，一整个[历史博物馆文件夹](https://github.com/DSPBluePrints/FactoryBluePrints/tree/main/%5B%E8%BF%87%E6%97%B6%5D%E5%8E%86%E5%8F%B2%E5%8D%9A%E7%89%A9%E9%A6%86%20%5BObsolete%5D%20History%20Museum)超过200mb的内容都是因为版本更新**彻底报废并且不再维护**的蓝图，这些蓝图可以理解成纯粹的垃圾，比历史提交更一无是处，但是也将永远留在蓝图仓库中。
再强调一遍，蓝图仓库旨在对社区作品进行完整的备份，而不是提供一个精悍的、经得起挑剔的蓝图包。用户下载一次要多花40秒，硬盘又多占了0.03%，到底是你从自己的角度真的需要这些？还是你凭感觉认为可能有人需要这些？
我不知道，但是蓝图仓库建立就是因为小马的蓝图群被封所以永远丢失了一批蓝图，后来也发生过gitee的莫名其妙封禁仓库，管理过程中操作失误导致的删库，社区构造出能让存档损坏的恶意蓝图，我们真的很需要数据安全。

**Comment by zxcvbnm3057** [comment]
我需要这个干嘛，直接手动指定depth简简单单，我感觉你们还是没有了解过我最初写的那两条git指令。

国内不做任何配置访问github根据所在地区与运营商有可能低至40kb/s或者甚至时间无连接，迅雷也基本没有加速效果，下载这多余的60mb真的只要四十几秒么。

另外之前我就有提到，历史编辑记录部分不包含在下载包里不影响蓝图集的完整性，或者是你们想保留谁做了什么贡献这种记录但是没什么好办法？有个通用的文件叫changelog可以考虑一下。

从小白玩家角度说，还是建议你们稍微考虑下不包含这部分数据吧吧。另外如果这个储存库只是用作收集纪念，可能就不太适合把这个宣传出去作为游戏蓝图下载地址，作为游戏的一部分，玩家的游戏体验才应该是最重要的吧，可下载这个蓝图集，首先下载过程并不能算是方便快捷，而且不是所有蓝图都有对应介绍。

最后还是感谢一下收集了这么多蓝图。自己挨个拍一遍筛选一下还是挺好用的

**Comment by zxcvbnm3057** [comment]
另外顺便问一下，这两天用的时候发现了一些蓝图堵氢或者堆叠机装反了之类的问题，改完直接提pr就行，还是要找署名作者申请一下编辑权限之类的？

**Comment by zxcvbnm3057** [comment]
说起来官方做的蓝图工具还是有点不完整，没有搜索功能，也没法分tag筛选，这么多蓝图堆在一起，想挨个写简介也确实是个累人的事

**Comment by bWFuanVzYWth** [comment]
> 另外顺便问一下，这两天用的时候发现了一些蓝图堵氢或者堆叠机装反了之类的问题，改完直接提pr就行，还是要找署名作者申请一下编辑权限之类的？

改完直接提交就行
