### ISSUE TITLE
感觉这个一塔一物石墨烯蓝图可能有点小问题

### ISSUE THREAD

**Issue by PrussianBlueCN** [DSPBluePrints/FactoryBluePrints#78]
一塔一物 one tower one thing/石墨烯.txt
好像是本项目里唯一一个高效石墨烯配方+量子化工厂的，但是这个配方产物有两个，蓝图里回塔带却只有一条，两产物混带回塔感觉很容易遇到一种产物满了卡住传送带导致另一种也回不去的情况，可能不是个好选择。另外看了一下一条传送带带了19个工厂，粗算一下满科技满带好像应该是30个，不知道是因为照顾低科技还是怎样。

**Comment by bWFuanVzYWth** [comment]
共用回塔带没有问题，是常见做法。但是检查后发现带的工厂数量确实存在严重问题，三级增产量子化工一条带应该只能带8个建筑，这个蓝图不仅建筑数量超了，甚至爪子还反了，基本上可以确定是低质量蓝图。
考虑到这个蓝图过于简单，所以不维护了直接删了。

**Comment by bWFuanVzYWth** [comment]
实际上一塔一物这个文件夹里的蓝图质量可能挺差的，不知道谁做的，可能是转了n手的魔改蓝图合集。群里讨论了一下以后可能会重制一套取代，不管怎么说还是建议尽量用黑盒
