### ISSUE TITLE
一塔一物：28800反物质:出货钩爪无效

### ISSUE THREAD

**Issue by CharlesYWL** [DSPBluePrints/FactoryBluePrints#85]
版本：v0.10.28.21219
钩爪抓不到对撞机头上的传送带
![image](https://github.com/DSPBluePrints/FactoryBluePrints/assets/34050457/6aa8bdba-7e99-421f-aaae-ff8147df3c39)

**Comment by bWFuanVzYWth** [comment]
群里投票后决定删除整个一塔一物文件夹，以后会出一套高质量的一塔一物蓝图
