### ISSUE TITLE
合集__通关前/氘燃料棒/氘燃料160: 疑似特性修复导致抓钩失效

### ISSUE THREAD

**Issue by mslxl** [DSPBluePrints/FactoryBluePrints#99]
![image](https://github.com/DSPBluePrints/FactoryBluePrints/assets/11132880/0ffce6d5-6bf8-49e4-a1c9-cc2c64eb7fda)

我在 B 站找到了相关教程 [0.25层传送带&制造台任意高度可进爪子](https://www.bilibili.com/video/BV1Qb4y1E75T/)，按照评论区中的恢复，这似乎并不是个例，而是在高度上升到一定程度后必然失效

**Comment by bWFuanVzYWth** [comment]
已移动到过时蓝图
